# Generated by Django 4.2.26 on 2025-11-24 08:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('operator', 'Operations Operator'), ('support', 'Support Staff'), ('viewer', 'View Only')], default='viewer', max_length=20, verbose_name='Role')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA Enabled')),
                ('mfa_secret', models.CharField(blank=True, max_length=32, verbose_name='MFA Secret')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Changed At')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
            ],
            options={
                'verbose_name': 'TMS User',
                'verbose_name_plural': 'TMS Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('offline', 'Offline'), ('error', 'Error'), ('high_cpu', 'High CPU Usage'), ('high_memory', 'High Memory Usage'), ('high_disk', 'High Disk Usage'), ('update_failed', 'Update Failed'), ('connection_lost', 'Connection Lost')], max_length=30, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Information')], default='MEDIUM', max_length=10, verbose_name='Severity')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Acknowledged')),
                ('acknowledged_by', models.CharField(blank=True, max_length=50, verbose_name='Acknowledged By')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_by', models.CharField(blank=True, max_length=50, verbose_name='Resolved By')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('auto_resolved', models.BooleanField(default=False, verbose_name='Auto Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Target Type')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='Target ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('request_path', models.TextField(blank=True, verbose_name='Request Path')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='Request Body')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='Response Status')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('company_name_kana', models.CharField(blank=True, max_length=100, verbose_name='Company Name (Kana)')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='Postal Code')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('contract_type', models.CharField(choices=[('basic', 'Basic Maintenance'), ('standard', 'Standard Maintenance'), ('premium', 'Premium Maintenance')], default='basic', max_length=20, verbose_name='Contract Type')),
                ('contract_start_date', models.DateField(verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_terminals', models.IntegerField(default=100, verbose_name='Max Terminals')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Customer Company',
                'verbose_name_plural': 'Customer Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Version')),
                ('model', models.CharField(default='TC-200', max_length=20, verbose_name='Model')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('file_hash', models.CharField(max_length=64, verbose_name='File Hash (SHA256)')),
                ('file_url', models.TextField(blank=True, verbose_name='File URL')),
                ('release_notes', models.TextField(blank=True, verbose_name='Release Notes')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Mandatory Update')),
                ('is_latest', models.BooleanField(default=False, verbose_name='Latest Version')),
                ('min_agent_version', models.CharField(blank=True, max_length=20, verbose_name='Minimum Agent Version')),
                ('released_date', models.DateField(verbose_name='Release Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Firmware Version',
                'verbose_name_plural': 'Firmware Versions',
                'ordering': ['-released_date'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Serial Number')),
                ('model', models.CharField(default='TC-200', max_length=20, verbose_name='Model')),
                ('store_name', models.CharField(max_length=100, verbose_name='Installation Store Name')),
                ('store_code', models.CharField(blank=True, max_length=20, verbose_name='Store Code')),
                ('installation_address', models.TextField(blank=True, verbose_name='Installation Address')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Under Maintenance')], default='offline', max_length=20, verbose_name='Status')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Firmware Version')),
                ('agent_version', models.CharField(blank=True, max_length=20, verbose_name='Agent Version')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Warranty End Date')),
                ('cpu_usage', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CPU Usage (%)')),
                ('memory_usage', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Memory Usage (%)')),
                ('disk_usage', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disk Usage (%)')),
                ('temperature', models.SmallIntegerField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('heartbeat_interval', models.IntegerField(default=300, verbose_name='Heartbeat Interval (seconds)')),
                ('auto_update_enabled', models.BooleanField(default=True, verbose_name='Auto Update Enabled')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='terminals.customer', verbose_name='Customer Company')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ['customer', 'store_name'],
            },
        ),
        migrations.CreateModel(
            name='UpdateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('firmware', 'Firmware Update'), ('config', 'Configuration Update'), ('reboot', 'Reboot'), ('diagnostic', 'Diagnostic')], max_length=20, verbose_name='Task Type')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=5, verbose_name='Priority')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='Created By')),
                ('firmware_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminals.firmwareversion', verbose_name='Firmware Version')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_tasks', to='terminals.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Update Task',
                'verbose_name_plural': 'Update Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('transaction', 'Transaction'), ('error', 'Error'), ('communication', 'Communication'), ('system', 'System'), ('update', 'Update')], max_length=20, verbose_name='Log Type')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='terminals.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Terminal Log',
                'verbose_name_plural': 'Terminal Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firmwareversion',
            index=models.Index(fields=['version', 'model'], name='terminals_f_version_d6e3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='firmwareversion',
            index=models.Index(condition=models.Q(('is_latest', True)), fields=['is_latest'], name='firmware_latest_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='alert',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='terminals.terminal', verbose_name='Terminal'),
        ),
        migrations.AddField(
            model_name='tmsuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='tmsuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='updatetask',
            index=models.Index(fields=['terminal'], name='terminals_u_termina_d8a7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='updatetask',
            index=models.Index(fields=['status'], name='terminals_u_status_cda598_idx'),
        ),
        migrations.AddIndex(
            model_name='updatetask',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['scheduled_at'], name='updatetask_sched_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='updatetask',
            index=models.Index(fields=['priority', 'scheduled_at'], name='terminals_u_priorit_5a4df3_idx'),
        ),
        migrations.AddIndex(
            model_name='terminallog',
            index=models.Index(fields=['terminal'], name='terminals_t_termina_33b4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='terminallog',
            index=models.Index(fields=['-created_at'], name='terminals_t_created_63b2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='terminallog',
            index=models.Index(fields=['log_type'], name='terminals_t_log_typ_d21a88_idx'),
        ),
        migrations.AddIndex(
            model_name='terminallog',
            index=models.Index(condition=models.Q(('log_level__in', ['ERROR', 'CRITICAL'])), fields=['log_level'], name='terminallog_error_critical_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['serial_number'], name='terminals_t_serial__0057af_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['customer', 'store_name'], name='terminals_t_custome_d481f6_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['status'], name='terminals_t_status_d81145_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['last_heartbeat'], name='terminals_t_last_he_a64703_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='terminals_a_user_id_2024aa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='terminals_a_created_ed7f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='terminals_a_action_1b7805_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='terminals_a_target__501551_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['terminal'], name='terminals_a_termina_c4216f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved'], name='terminals_a_is_reso_fa60cf_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='terminals_a_created_907c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['severity'], name='alert_severity_unresolved_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='terminals_a_alert_t_783f22_idx'),
        ),
    ]
